package com.micdm.smsgraphs.events;

public enum EventType {
    START_LOAD_MESSAGES,
    PROGRESS_LOAD_MESSAGES,
    FINISH_LOAD_MESSAGES,
    REQUEST_LOAD_OPERATION_REPORT,
    LOAD_OPERATION_REPORT,
    REQUEST_LOAD_CATEGORIES,
    LOAD_CATEGORIES,
    REQUEST_LOAD_TARGETS,
    LOAD_TARGETS,
    REQUEST_LOAD_OPERATIONS,
    LOAD_OPERATIONS,
    REQUEST_SET_OPERATION_IGNORED,
    EDIT_CATEGORY,
    REQUEST_EDIT_TARGET,
    EDIT_TARGET,
    REQUEST_MONTH_OPERATIONS,
    REQUEST_SELECT_MONTH
}
